# frozen_string_literal: true

# ProblemChecker class
# This class is responsible for checking if the user's answer is correct.
# It compares the user's answer with the answer generated by the ProblemGenerator.
class ProblemChecker
  def self.correct?(problem:, user_answer:)
    user_answer == problem.answer
  end
end
