# frozen_string_literal: true

# Problem class
# This class is responsible for storing the problem generated by the ProblemGenerator class.
# It stores the operator, operands, and answer for the problem.
class Problem
  attr_reader :operator, :operands, :answer

  def initialize(operator, operands, answer)
    @operator = operator
    @operands = operands
    @answer = answer
  end

  def print
    puts "#{@operands.join(" #{@operator} ")} = ?"
  end
end
